# Generated by Django 3.0.5 on 2020-04-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='additional_info',
            field=models.CharField(default='hi', max_length=25),
            preserve_default=False,
        ),
    ]
