# Generated by Django 3.0.5 on 2020-04-07 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='additional_info',
        ),
    ]
