# Generated by Django 3.0.5 on 2020-04-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_ting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ting',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
