# Generated by Django 3.0.5 on 2020-04-08 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200407_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ting',
        ),
    ]
